# Generated by Django 5.2 on 2025-06-30 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('prioritas', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('sla', models.DateTimeField(blank=True, null=True)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_diperbarui', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='unggahan/')),
                ('cabang', models.CharField(default='-', max_length=100)),
                ('jabatan', models.CharField(default='-', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Tiket.tiket')),
            ],
        ),
    ]
