# Generated by Django 5.2 on 2025-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=50),
        ),
    ]
