# Generated by Django 5.2 on 2025-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='divisi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ttl',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
