# Generated by Django 5.2 on 2025-07-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_alamat_remove_customuser_divisi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='office_branch',
            new_name='kantor_cabang',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fullname',
            new_name='nama_lengkap',
        ),
    ]
