# Generated by Django 5.2 on 2025-07-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiket', '0003_alter_tiket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Tiket berhasil dikirim'), ('ticket_failed', 'Tiket tidak berhasil dikirim'), ('ticket_updated', 'Tiket berhasil diperbarui'), ('ticket_in_progress', 'Tiket dalam in progress'), ('ticket_completed', 'Tiket selesai'), ('password_updated', 'Password berhasil diperbarui'), ('profile_updated', 'Profile berhasil diperbarui'), ('ticket_created', 'Tiket berhasil dikirim'), ('ticket_failed', 'Tiket tidak berhasil dikirim'), ('ticket_updated', 'Tiket berhasil diperbarui'), ('ticket_in_progress', 'Tiket dalam in progress'), ('ticket_completed', 'Tiket selesai'), ('password_updated', 'Password berhasil diperbarui'), ('profile_updated', 'Profile berhasil diperbarui'), ('user_updated', 'Data user berhasil diperbarui'), ('user_created', 'User berhasil ditambahkan')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tiket.tiket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
